export const NEPAL_DISTRICTS = [
  'Kathmandu', 'Kaski (Pokhara)', 'Lalitpur', 'Bhaktapur', 'Chitwan', 'Rupandehi (Butwal/Bhairahawa)',
  'Morang (Biratnagar)', 'Jhapa', 'Sunsari (Dharan)', 'Parsa (Birgunj)', 'Banke (Nepalgunj)', 'Kailali (Dhangadhi)',
  'Dhanusha (Janakpur)', 'Makwanpur (Hetauda)', 'Gorkha', 'Tanahun', 'Syangja', 'Baglung', 'Palpa', 'Nawalpur',
  'Parasi', 'Dang', 'Surkhet', 'Bardiya', 'Kanchanpur', 'Ilam', 'Dhankuta', 'Sindhupalchok', 'Kavrepalanchok',
  'Nuwakot', 'Dhading', 'Ramechhap', 'Dolakha', 'Sindhuli', 'Sarlahi', 'Mahottari', 'Rautahat', 'Bara', 'Kapilvastu',
  'Arghakhanchi', 'Gulmi', 'Pyuthan', 'Rolpa', 'Salyan', 'Rukum', 'Dailekh', 'Jajarkot', 'Jumla', 'Kalikot', 'Achham',
  'Doti', 'Bajhang', 'Bajura', 'Baitadi', 'Darchula', 'Dadeldhura', 'Okhaldhunga', 'Khotang', 'Bhojpur', 'Sankhuwasabha',
  'Solukhumbu', 'Taplejung', 'Panchthar', 'Terhathum', 'Manang', 'Mustang', 'Lamjung', 'Parbat', 'Myagdi', 'Dolpa',
  'Mugu', 'Humla'
];

export const US_UNIVERSITIES = [
  'Midwestern State University',
  'Midwestern University (Downers Grove/Glendale)',
  'University of North Texas',
  'University of Texas at Arlington',
  'University of Texas at Dallas',
  'Texas A&M University',
  'University of Houston',
  'University of South Florida',
  'Florida International University',
  'University of Central Florida',
  'Arizona State University',
  'University of Arizona',
  'San Jose State University',
  'California State University, Northridge',
  'California State University, Long Beach',
  'San Francisco State University',
  'University of Maryland, Baltimore County',
  'George Mason University',
  'Purdue University',
  'University of Illinois Chicago',
  'New York University (NYU)',
  'Northeastern University',
  'University of Cincinnati',
  'Kent State University',
  'Cleveland State University',
  'Wright State University',
  'University of Colorado Denver',
  'Colorado State University',
  'Wichita State University',
  'University of New Haven',
  'University of Bridgeport',
  'Trine University',
  'Western Illinois University',
  'Southern Illinois University Carbondale',
  'St. Cloud State University',
  'Minnesota State University, Mankato',
  'University of Louisiana at Monroe',
  'Louisiana Tech University',
  'Arkansas State University',
  'University of Arkansas',
  'University of Idaho',
  'Troy University',
  'University of Alabama at Birmingham',
  'University of North Dakota',
  'South Dakota State University',
  'University of Memphis',
  'Western Kentucky University',
  'Eastern Michigan University',
  'Central Michigan University',
  'Wayne State University',
  'University of Wisconsin-Milwaukee',
  'Georgia State University',
  'Kennesaw State University',
  'University of Utah',
  'Iowa State University',
  'University of Kansas',
  'State University of New York (SUNY) Buffalo',
  'Pace University',
  'Illinois Institute of Technology',
  'Stevens Institute of Technology',
  'Rochester Institute of Technology',
  'DePaul University',
  'Auburn University',
  'University of Nebraska-Lincoln',
  'University of Oklahoma',
  'Oklahoma State University',
  'University of Missouri',
  'University of Kentucky',
  'West Virginia University',
  'University of Dayton',
  'University of Toledo',
  'Youngstown State University'
];

export const MAJORS_LIST = [
  'Computer Science',
  'Computer Engineering',
  'Cybersecurity & Network Defense',
  'Data Science & Big Data Analytics',
  'Software Engineering & Cloud Computing',
  'Information Technology (IT)',
  'Artificial Intelligence & Machine Learning',
  'Business Administration (BBA / General MBA)',
  'Business Analytics & Information Systems',
  'Finance & Investment Banking',
  'Accounting & Auditing',
  'Commercial Aviation & Professional Pilot Studies',
  'Mechanical Engineering',
  'Civil & Structural Engineering',
  'Electrical & Computer Systems Engineering',
  'Biomedical Engineering & Bio-devices',
  'Public Health (MPH / Epidemiology)',
  'Nursing Practice & Health Administration',
  'Biotechnology & Molecular Biology',
  'Supply Chain & Global Logistics',
  'Marketing Management & Digital Strategy',
  'Economics & Financial Econometrics',
  'Hospitality & International Tourism Management',
  'Environmental Science & Sustainability',
  'International Relations & Strategic Studies',
  'Mathematics & Actuarial Science'
];

export const NEPAL_OCCUPATIONS = [
  'Government Officer (Gazetted / Civil Service)',
  'Registered Commercial Business / Import-Export',
  'Agriculture & Commercial Landowner',
  'Banking & Financial Sector Executive',
  'Medical Doctor / Senior Healthcare Specialist',
  'Chartered Accountant (CA) / Audit Firm',
  'Software Engineer / IT Professional',
  'University Professor / School Principal',
  'Foreign Employment / Remittance Dependent',
  'Civil Engineer / Construction Contractor',
  'Tourism / Trekking & Hotel Entrepreneur',
  'Retired with Government Pension & Rental Properties',
  'Unemployed / Informal Unregistered Income'
];